// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hello.proto

package validator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *FieldValidator) Validate() error {
	return nil
}
